/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package m.rhem;

import csip.Config;
import java.util.Set;
import javax.ws.rs.core.Application;
import org.glassfish.jersey.media.multipart.MultiPartFeature;

/**
 *
 * @author User
 */
@javax.ws.rs.ApplicationPath("")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(MultiPartFeature.class);
        addRestResourceClasses(resources);
        Config.registry().register(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(csip.ArchiveService.class);
        resources.add(csip.CatalogService.class);
        resources.add(csip.ControlService.class);
        resources.add(csip.QueryService.class);
        resources.add(csip.ReportService.class);
        resources.add(csip.UIService.class);
        resources.add(m.rhem.V1_0.class);
        resources.add(m.rhem.rhem01_runmodel.V1_0.class);
        resources.add(m.rhem.rhem02_getclimatestations.V1_0.class);
        resources.add(m.rhem.rhem03_compEsd.V1_0.class);
        resources.add(m.rhem.rhem03_compEsd.V2_0.class);
        resources.add(m.rhem.rhem04_surfacetextureclasses.V1_0.class);
        resources.add(m.rhem.rhem05_slopeShapes.V1_0.class);
        resources.add(m.rhem.rhem06_riskassessment.V1_0.class);
        resources.add(m.rhem.rhem07_editparfile.V1_0.class);
    }
}
